name: todo_list
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: 
  introduction_screen: ^3.0.0
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  path: ^1.9.0
  sqflite_common_ffi: ^2.0.0
  provider: ^6.1.2
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  google_sign_in:
  cloud_firestore:
  flutter_svg: ^2.0.17
  get_storage: 
  firebase_storage: 
  image_picker:
  mime: ^1.0.6





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  flutter_lints: ^5.0.0
dependency_overrides:
  http: ^1.0.0
  uuid: ^3.0.3

flutter:

  uses-material-design: true
  assets:
    - assets/svgs/

  fonts:
    - family: intro
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf